/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNISample */

#ifndef _Included_JNISample
#define _Included_JNISample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNISample
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNISample_sayHello
  (JNIEnv *, jobject);
  

#ifdef __cplusplus
}
#endif
#endif
